package uva.ipc.practica1.vista;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import uva.ipc.practica1.modelo.Biblioteca;
import uva.ipc.practica1.modelo.Libro;
import uva.ipc.practica1.modelo.Biblioteca;
//18/3/2023
/**
 * Clase VistaEdicionManual
 * @author dansana
 * @author saant
 */
public class VistaEdicionManual extends javax.swing.JFrame {
    private ArrayList<Libro> historial;
    private DefaultListModel <String> lista = new DefaultListModel<>();
    private ControladorEdicionManual miControlador;
    private boolean actualizar = false;
    private int index;
    private Biblioteca miBiblioteca;
    
    /**
     * Constructor por defecto de la clase VistaPractica1
     * Inicializa todos los componentes de la interfaz con el método initComponents()
     * y crea el objeto miControlador, para manejar los eventos de la interfaz 
     */
    
    public VistaEdicionManual() {
        initComponents();
        miControlador=new ControladorEdicionManual(this);
//        historial=miBiblioteca.getHistorial();
//        cargarLista(lista,historial);
        //this.miModelo=new Biblioteca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        VolverAMenuButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tituloTextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        descripcionScrollPane = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        ISBNLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ISBNTextField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        estadoLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        precioLabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        precioSpinner = new javax.swing.JSpinner();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        leidoCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        librosScrollPane = new javax.swing.JScrollPane();
        librosList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 500));
        setPreferredSize(new java.awt.Dimension(716, 500));

        jPanel2.setBackground(new java.awt.Color(200, 216, 223));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setText("            ");
        jPanel2.add(errorLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(200, 216, 223));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(200, 216, 223));

        VolverAMenuButton.setBackground(new java.awt.Color(248, 160, 97));
        VolverAMenuButton.setForeground(new java.awt.Color(37, 50, 66));
        VolverAMenuButton.setText("Volver al menu");
        VolverAMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAMenuButtonActionPerformed(evt);
            }
        });
        jPanel5.add(VolverAMenuButton);

        guardarButton.setBackground(new java.awt.Color(248, 160, 97));
        guardarButton.setForeground(new java.awt.Color(37, 50, 66));
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(guardarButton);

        editarButton.setBackground(new java.awt.Color(248, 160, 97));
        editarButton.setForeground(new java.awt.Color(37, 50, 66));
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(editarButton);

        borrarButton.setBackground(new java.awt.Color(248, 160, 97));
        borrarButton.setForeground(new java.awt.Color(37, 50, 66));
        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });
        jPanel5.add(borrarButton);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(200, 216, 223));
        jPanel6.setLayout(new java.awt.GridLayout(6, 2));

        jPanel7.setBackground(new java.awt.Color(200, 216, 223));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tituloLabel.setForeground(new java.awt.Color(37, 50, 66));
        tituloLabel.setText("Título");
        tituloLabel.setToolTipText("");
        tituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(tituloLabel);

        jPanel6.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(200, 216, 223));

        tituloTextField.setColumns(13);
        jPanel8.add(tituloTextField);

        jPanel6.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(200, 216, 223));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        descripcionLabel.setForeground(new java.awt.Color(37, 50, 66));
        descripcionLabel.setText("Descripción");
        jPanel9.add(descripcionLabel);

        jPanel6.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        descripcionTextArea.setColumns(13);
        descripcionTextArea.setRows(10);
        descripcionScrollPane.setViewportView(descripcionTextArea);

        jPanel10.add(descripcionScrollPane);

        jPanel6.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(200, 216, 223));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ISBNLabel.setForeground(new java.awt.Color(37, 50, 66));
        ISBNLabel.setText("ISBN");
        jPanel11.add(ISBNLabel);

        jPanel6.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(200, 216, 223));

        ISBNTextField.setColumns(13);
        jPanel12.add(ISBNTextField);

        jPanel6.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(200, 216, 223));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        estadoLabel.setForeground(new java.awt.Color(37, 50, 66));
        estadoLabel.setText("Estado");
        jPanel13.add(estadoLabel);

        jPanel6.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(200, 216, 223));

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Regular", "Malo" }));
        jPanel14.add(estadoComboBox);

        jPanel6.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(200, 216, 223));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        precioLabel.setForeground(new java.awt.Color(37, 50, 66));
        precioLabel.setText("Precio");
        jPanel15.add(precioLabel);

        jPanel6.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(200, 216, 223));

        precioSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        precioSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel16.add(precioSpinner);

        jPanel6.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(200, 216, 223));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(200, 216, 223));

        leidoCheckBox.setForeground(new java.awt.Color(37, 50, 66));
        leidoCheckBox.setText("Ya lo he leído");
        jPanel18.add(leidoCheckBox);

        jPanel6.add(jPanel18);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        librosScrollPane.setViewportView(librosList);

        jPanel4.add(librosScrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método para controlar el evento de pulsar el botón Guardar
     * @param evt Evento que se genera al pulsar el botón Guardar
     */
    
    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        miControlador.procesaEventoGuardar(actualizar,lista);
    }//GEN-LAST:event_guardarButtonActionPerformed
    
    /**
     * Método para controlar el evento de pulsar el botón Editar
     * @param evt Evento que se genera al pulsar el botón Editar
     */
    
    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        miControlador.procesaEventoEditar();
    }//GEN-LAST:event_editarButtonActionPerformed
    
    /**
     * Método para controlar el evento de pulsar el botón Borrar
     * @param evt Evento que se genera al pulsar el botón Borrar
     */
    
    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        miControlador.procesaEventoBorrar(lista);
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void VolverAMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAMenuButtonActionPerformed
        miControlador.procesaEventoVolverAMenu();
    }//GEN-LAST:event_VolverAMenuButtonActionPerformed
    
    /**
     * Método que muestra el mensaje en la interfaz
     * @param mensaje Mensaje que se quiere mostrar en la interfaz
     * @param isError
     */
   
    public void mostrarMensaje(String mensaje, boolean isError) { 
        if(isError){
            errorLabel.setForeground(Color.red);
        }else{
            errorLabel.setForeground(Color.black);
        }
        errorLabel.setText(mensaje);
    }
    
    public Libro GetLibro(){
        String titulo=tituloTextField.getText();
        String descripcion=descripcionTextArea.getText();
        String ISBN=(String)(ISBNTextField.getText());
        String estado=(String)estadoComboBox.getSelectedItem();
        double precio=(double)precioSpinner.getValue();
        boolean leido=leidoCheckBox.isSelected();
        
        return new Libro(titulo,descripcion, ISBN, estado,precio,leido);   
    }
    
    public void addLibroLista(DefaultListModel <String> lista, Libro libroNuevo){
        lista.addElement("Título: "+libroNuevo.getTitulo()+" ISBN: "+libroNuevo.getISBN());
        librosList.setModel(lista);
    }
    
    public void setLibroLista(DefaultListModel <String> lista, Libro libroNuevo,int index){
        lista.set(index, "Título: "+libroNuevo.getTitulo()+" ISBN: "+libroNuevo.getISBN());
        librosList.setModel(lista);
    }
    
    public void borrarLibroLista(DefaultListModel <String> lista,int index){
        lista.remove(index);
        librosList.setModel(lista);
    }
    
    public void cargarLista(DefaultListModel <String> lista,ArrayList <Libro> historial){
        for(Libro libro:historial){
            addLibroLista(lista,libro);
        }
    }
    
    public int getIndex(){
        return index;
    }
    public int selectedIndex(){
        return this.librosList.getSelectedIndex();
    }
    
    public void setIndex(int index){
        this.index=index;
    }
    
    public void setValores(int index,ArrayList <Libro> historial){
        tituloTextField.setText(historial.get(index).getTitulo());
        descripcionTextArea.setText(historial.get(index).getDescripcion());
        ISBNTextField.setText(historial.get(index).getISBN());
        estadoComboBox.setSelectedItem(historial.get(index).getEstado());
        precioSpinner.setValue((Object)historial.get(index).getPrecio());
        leidoCheckBox.setSelected((historial.get(index).getLeido()));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISBNLabel;
    private javax.swing.JTextField ISBNTextField;
    private javax.swing.JButton VolverAMenuButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JScrollPane descripcionScrollPane;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JButton guardarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox leidoCheckBox;
    private javax.swing.JList<String> librosList;
    private javax.swing.JScrollPane librosScrollPane;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JSpinner precioSpinner;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField tituloTextField;
    // End of variables declaration//GEN-END:variables
}
