/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.practica1.vista;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import uva.ipc.practica1.modelo.Biblioteca;
import uva.ipc.practica1.modelo.Libro;

/**
 *
 * @author saant
 */
public class VistaBuscador extends javax.swing.JFrame {
    private ControladorBuscador miControlador;
    private Biblioteca miBiblioteca;
    private boolean buscarTitulo;
    private DefaultListModel <String> lista = new DefaultListModel<>();
    //ArrayList <Libro> historial=miBiblioteca.getHistorial();
    /**
     * Creates new form VistaBuscador
     */
    public VistaBuscador() {
        initComponents();
        miControlador=new ControladorBuscador(this);
    }
    
    //cargaLista(lista,miBiblioteca.getHistorial());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buscadorTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tituloRadioButton = new javax.swing.JRadioButton();
        isbnRadioButton = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        editarButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        librosTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        volverMenu = new javax.swing.JMenu();
        archivoMenu = new javax.swing.JMenu();
        addLibrosFicheroMenuItem = new javax.swing.JMenuItem();
        guardarLibrosMenuItem = new javax.swing.JMenuItem();
        ordenarMenu = new javax.swing.JMenu();
        ordenaPorNombreMenuItem = new javax.swing.JMenuItem();
        ordenaPorPrecioMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(248, 160, 97));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBackground(new java.awt.Color(200, 216, 223));

        buscadorTextField.setColumns(12);
        buscadorTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscadorTextField.setActionCommand("<Not Set>");
        buscadorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorTextFieldKeyPressed(evt);
            }
        });
        jPanel3.add(buscadorTextField);

        buscarButton.setBackground(new java.awt.Color(248, 160, 97));
        buscarButton.setForeground(new java.awt.Color(37, 50, 66));
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        jPanel3.add(buscarButton);

        jPanel1.add(jPanel3);

        jPanel6.setBackground(new java.awt.Color(200, 216, 223));

        errorLabel.setText("Posibles excepciones");
        jPanel6.add(errorLabel);

        jPanel1.add(jPanel6);

        jPanel4.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setBackground(new java.awt.Color(200, 216, 223));

        busquedaButtonGroup.add(tituloRadioButton);
        tituloRadioButton.setForeground(new java.awt.Color(37, 50, 66));
        tituloRadioButton.setSelected(true);
        tituloRadioButton.setText("Título");
        tituloRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(tituloRadioButton);

        busquedaButtonGroup.add(isbnRadioButton);
        isbnRadioButton.setForeground(new java.awt.Color(37, 50, 66));
        isbnRadioButton.setText("ISBN");
        isbnRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(isbnRadioButton);

        jPanel2.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(200, 216, 223));

        editarButton.setBackground(new java.awt.Color(248, 160, 97));
        editarButton.setForeground(new java.awt.Color(37, 50, 66));
        editarButton.setText("Editar libro");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        jPanel9.add(editarButton);

        jPanel2.add(jPanel9);

        jPanel4.add(jPanel2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        librosTable.setBackground(new java.awt.Color(233, 242, 242));
        librosTable.setForeground(new java.awt.Color(37, 50, 66));
        librosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Precio", "ISBN"
            }
        ));
        librosTable.setGridColor(new java.awt.Color(171, 193, 205));
        librosTable.setSelectionForeground(new java.awt.Color(37, 50, 66));
        jScrollPane1.setViewportView(librosTable);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(214, 231, 231));

        volverMenu.setText("Volver");
        volverMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                volverMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(volverMenu);

        archivoMenu.setText("Archivo");

        addLibrosFicheroMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addLibrosFicheroMenuItem.setText("Añadir libros mediante archivo .txt");
        addLibrosFicheroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibrosFicheroMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(addLibrosFicheroMenuItem);

        guardarLibrosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardarLibrosMenuItem.setText("Guardar libros un un archivo .txt");
        guardarLibrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarLibrosMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(guardarLibrosMenuItem);

        jMenuBar1.add(archivoMenu);

        ordenarMenu.setText("Ordenar por...");

        ordenaPorNombreMenuItem.setText("Nombre");
        ordenaPorNombreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaPorNombreMenuItemActionPerformed(evt);
            }
        });
        ordenarMenu.add(ordenaPorNombreMenuItem);

        ordenaPorPrecioMenuItem.setText("Precio");
        ordenaPorPrecioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaPorPrecioMenuItemActionPerformed(evt);
            }
        });
        ordenarMenu.add(ordenaPorPrecioMenuItem);

        jMenuBar1.add(ordenarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarLibrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarLibrosMenuItemActionPerformed
        JFrame frame=new JFrame("Guardar en un fichero");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showOpenDialog(frame);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Continuar con la creación del archivo
            File ficheroSeleccionado = fileChooser.getSelectedFile();
            String ruta = ficheroSeleccionado.getAbsolutePath();
            mostrarMensaje("Se ha guardado en "+ficheroSeleccionado.getName(),false);
            miControlador.procesaEventoGuardarLibros(ficheroSeleccionado);
        } else {
            // El usuario ha cancelado la selección
            mostrarMensaje("Operación cancelada",true);
        }
    }//GEN-LAST:event_guardarLibrosMenuItemActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        miControlador.procesaEventoEditarLibro();
    }//GEN-LAST:event_editarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        buscarTitulo=tituloRadioButton.isSelected();
        miControlador.procesaEventoBuscar(lista,buscarTitulo);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void addLibrosFicheroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibrosFicheroMenuItemActionPerformed
        Object[] options = {"Sobreescribir lista","Añadir a la lista","Cancelar"};
        int n =JOptionPane.showOptionDialog(null, "¿Desea sobreescribir o añadir los libros del fichero a la lista actual?","Sobreescribir lista",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null,options,options[2]);
        
        if(n==0 || n==1){ //sobreescribir lista==0 y mantener lista==1, cancelar==2
            JFrame frame=new JFrame("Selecciona");
            JFileChooser fileChooser=new JFileChooser();
            fileChooser.setDialogTitle("Selecciona un archivo");
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
            fileChooser.setFileFilter(filter);
            int resultado=fileChooser.showOpenDialog(frame);
            if(resultado==JFileChooser.APPROVE_OPTION){
                File archivoSeleccionado=fileChooser.getSelectedFile();
                //TODO:solucionar
                String ruta = archivoSeleccionado.getAbsolutePath();
                mostrarMensaje(archivoSeleccionado.getName()+" abierto.",false);
                
                miControlador.procesaEventoAddLibrosFichero(lista,ruta,n);
            }else{
                mostrarMensaje("Operación cancelada",true);
            }
        }else{
            mostrarMensaje("Operación cancelada",true);
        }
                
    }//GEN-LAST:event_addLibrosFicheroMenuItemActionPerformed

    private void ordenaPorNombreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaPorNombreMenuItemActionPerformed
        miControlador.procesaEventoOrdenaPorNombre();
    }//GEN-LAST:event_ordenaPorNombreMenuItemActionPerformed

    private void ordenaPorPrecioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaPorPrecioMenuItemActionPerformed
        miControlador.procesaEventoOrdenaPorPrecio();
    }//GEN-LAST:event_ordenaPorPrecioMenuItemActionPerformed

    private void volverMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_volverMenuMenuSelected
        miControlador.procesaEventoVolver();
    }//GEN-LAST:event_volverMenuMenuSelected

    private void buscadorTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorTextFieldKeyPressed
        if(evt.getKeyCode()==10){
            buscarTitulo=tituloRadioButton.isSelected();
            miControlador.procesaEventoBuscar(lista,buscarTitulo);
        }
        
    }//GEN-LAST:event_buscadorTextFieldKeyPressed
     
    public void mostrarMensaje(String mensaje, boolean isError) { 
        if(isError){
            errorLabel.setForeground(Color.red);
        }else{
            errorLabel.setForeground(Color.black);
        }
        errorLabel.setText(mensaje);
    }

    public void mostrarError(int tipoError){
        errorLabel.setForeground(Color.red);
        //hacer un switch dependiendo los errores q pueda dar
//        error 1: estructura del fichero incorrecta
//        error 2: error desconocido
    }
    
    public String getCadenaBuscar(){
        return buscadorTextField.getText();
    }
    /*
    public void addLibroLista(DefaultListModel <String> lista, Libro libroBuscador){
        lista.addElement("Título: "+libroBuscador.getTitulo()+"Precio: "+libroBuscador.getPrecio()+ "ISBN: "+libroBuscador.getISBN());
        BuscadorList.setModel(lista);
    }
    
    public void cargaLista(DefaultListModel <String> lista, ArrayList <Libro> historial){
        Libro libroAdd;
        for(int i=0;i>lista.size();i++){
            libroAdd=historial.get(i);
            lista.addElement("Título: "+libroAdd.getTitulo()+"Precio: "+libroAdd.getPrecio()+ "ISBN: "+libroAdd.getISBN());
        }
        BuscadorList.setModel(lista);
    }
    */
    public void cargarTabla(String[][] data){
        String [] columnNames={"Título","Precio","ISBN"};
        DefaultTableModel librosDefaultTable= new DefaultTableModel(data, columnNames);
        librosTable.setModel(librosDefaultTable);
        librosDefaultTable.fireTableDataChanged();


    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addLibrosFicheroMenuItem;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JTextField buscadorTextField;
    private javax.swing.JButton buscarButton;
    private javax.swing.ButtonGroup busquedaButtonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JMenuItem guardarLibrosMenuItem;
    private javax.swing.JRadioButton isbnRadioButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable librosTable;
    private javax.swing.JMenuItem ordenaPorNombreMenuItem;
    private javax.swing.JMenuItem ordenaPorPrecioMenuItem;
    private javax.swing.JMenu ordenarMenu;
    private javax.swing.JRadioButton tituloRadioButton;
    private javax.swing.JMenu volverMenu;
    // End of variables declaration//GEN-END:variables
}
